export const formData = {
    "elements":  [
          {
            "id": "1",
            "taskType": "Meeting",
            "dueDate": "2024-03-01",
            "dueTime": "10:00 AM",
            "createdDate": "2024-02-28",
            "createdBy": "John Doe",
            "completedDate": null,
            "title": "Client Meeting",
            "description": "Discuss project details with the client",
            "status": "In Progress",
            "owner": "Alice",
            "outcome": null,
            "collaborators": ["Bob", "Charlie"]
          },
          {
            "id": "2",
            "taskType": "Assignment",
            "dueDate": "2024-03-05",
            "dueTime": "2:30 PM",
            "createdDate": "2024-03-01",
            "createdBy": "Jane Smith",
            "completedDate": null,
            "title": "Coding Task",
            "description": "Implement new features",
            "status": "Pending",
            "owner": "Eva",
            "outcome": null,
            "collaborators": ["David", "Emily"]
          },
          {
            "id": "3",
            "taskType": "Review",
            "dueDate": "2024-03-10",
            "dueTime": "3:45 PM",
            "createdDate": "2024-03-05",
            "createdBy": "Bob Johnson",
            "completedDate": null,
            "title": "Project Review",
            "description": "Review project progress and plan for next steps",
            "status": "Upcoming",
            "owner": "Chris",
            "outcome": null,
            "collaborators": ["Frank", "Grace"]
          },
          {
            "id": "4",
            "taskType": "Task",
            "dueDate": "2024-03-15",
            "dueTime": "9:00 AM",
            "createdDate": "2024-03-10",
            "createdBy": "Alice Williams",
            "completedDate": null,
            "title": "New Project Kickoff",
            "description": "Start working on the new project",
            "status": "In Progress",
            "owner": "Harry",
            "outcome": null,
            "collaborators": ["Ivy", "Jack"]
          },
          {
            "id": "5",
            "taskType": "Event",
            "dueDate": "2024-03-20",
            "dueTime": "6:00 PM",
            "createdDate": "2024-03-15",
            "createdBy": "Chris Davis",
            "completedDate": null,
            "title": "Team Building Event",
            "description": "Team-building activities and dinner",
            "status": "Pending",
            "owner": "Kathy",
            "outcome": null,
            "collaborators": ["Liam", "Mia"]
          },
          {
            "id": "6",
            "taskType": "Meeting",
            "dueDate": "2024-03-25",
            "dueTime": "11:30 AM",
            "createdDate": "2024-03-20",
            "createdBy": "Sara Johnson",
            "completedDate": null,
            "title": "Weekly Team Meeting",
            "description": "Discuss project updates and challenges",
            "status": "Upcoming",
            "owner": "Mike",
            "outcome": null,
            "collaborators": ["Nina", "Oliver"]
          },
          {
            "id": "7",
            "taskType": "Assignment",
            "dueDate": "2024-03-30",
            "dueTime": "4:15 PM",
            "createdDate": "2024-03-25",
            "createdBy": "David White",
            "completedDate": null,
            "title": "Documentation Task",
            "description": "Prepare project documentation",
            "status": "Pending",
            "owner": "Patty",
            "outcome": null,
            "collaborators": ["Quincy", "Rachel"]
          }
        ]
  }