export const meetingData={
    data:[
      {
        lead:'John Smith',
        title:'Lead Management Meeting',
        location:'Bangalore',
        description:'This is about the lead management project',
        timeZone:'Eastern Standard Time',
        attendees:'Jane Smith',
        fromDate:'2024-03-02',
        toDate:'2024-03-21',
        allDay:'True',
      },
      {
        lead: 'Jane Johnson',
        title: 'Project Discussion Meeting',
        location: 'New York',
        description: 'Discussion on project updates and challenges',
        timeZone: 'Coordinated Universal Time',
        attendees: 'John Doe',
        fromDate: '2024-03-05',
        toDate: '2024-03-10',
        allDay: 'True',
      },
      {
        lead: 'Michael Brown',
        title: 'Client Presentation Meeting',
        location: 'London',
        description: 'Presentation of project progress to the client',
        timeZone: 'Central European Time',
        attendees: 'Alice Mark',
        fromDate: '2024-03-10',
        toDate: '2024-03-13',
        allDay: 'False',
      },
      {
        lead: 'Emily Jones',
        title: 'Team Collaboration Meeting',
        location: 'Los Angeles',
        description: 'Collaboration session to brainstorm ideas',
        timeZone: 'Pacific Standard Time',
        attendees: 'Kate Winslet',
        fromDate: '2024-03-15',
        toDate: '2024-03-20',
        allDay: 'True',
      },
      {
        lead: 'William Garcia',
        title: 'Product Demo Meeting',
        location: 'Mumbai',
        description: 'Demonstration of new product features',
        timeZone: 'India Standard Time',
        attendees: 'William Henry',
        fromDate: '2024-03-20',
        toDate: '2024-03-23',
        allDay: 'False',
      },
      {
        lead: 'Jane Johnson',
        title: 'Planning Meeting',
        location: 'Paris',
        description: 'Planning session for upcoming projects',
        timeZone: 'Central European Time',
        attendees: 'Jane Peter',
        fromDate: '2024-03-25',
        toDate: '2024-03-27',
        allDay: 'True',
      },
      {
        lead: 'Michael Brown',
        title: 'Team Building Meeting',
        location: 'Sydney',
        description: 'Team-building activities and bonding session',
        timeZone: 'Coordinated Universal Time',
        attendees: 'Carley Wilson',
        fromDate: '2024-03-28',
        toDate: '2024-03-30',
        allDay: 'False',
      }
    ]
}